version: '3'

services:

  api:
    image: node:fermium-alpine
    command: yarn start:dev
    depends_on:
      - postgres
    ports:
      - "3333:3333"
      - "9229:9229"
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - nest-api

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 'docker'
    ports:
      - '5432:5432'
    networks:
      - nest-api

networks:
  nest-api:
