name: check

on:
  push:
    branches:
      '*'

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

        working-directory: ./backend

      - run: yarn --frozen-lockfile
        name: Install dependencies

      - run: yarn lint
        name: Lint

      - run: docker-compose up -d postgres
        name: Start infrastructure

      - run: yarn test:e2e
        name: Tests

      - run: docker-compose down
        name: Dispose infrastructure
